import localFont from "next/font/local";
import "./globals.css";

const mercuryFont = localFont({ src: "./Mercury.otf", formats: "otf" });

export const metadata = {
  title: "for lily",
  description: "Generated by Kyra"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={mercuryFont.className}>{children}</body>
    </html>
  );
}
